# Generated by Django 5.1.4 on 2024-12-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
