# Generated by Django 5.1.4 on 2024-12-08 02:19

import django.db.models.deletion
import user.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istourist', models.BooleanField(verbose_name='istourist')),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.utils.user_pph)),
                ('displayname', models.CharField(blank=True, max_length=30, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
