# Generated by Django 5.1.4 on 2024-12-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio_fileEN', models.FileField(upload_to='audio_files/EN')),
                ('audio_fileGR', models.FileField(upload_to='audio_files/GR')),
                ('audio_fileRUS', models.FileField(upload_to='audio_files/RUS')),
                ('audio_fileAR', models.FileField(upload_to='audio_files/AR')),
                ('descriptionEN', models.TextField(blank=True)),
                ('descriptionGR', models.TextField(blank=True)),
                ('descriptionRUS', models.TextField(blank=True)),
                ('descriptionAR', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
